# Generated by Django 4.1.7 on 2023-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('J', 'Jewelery'), ('MC', "Men's Clothing"), ('WC', "Women's Clothing")], default='E', max_length=2)),
            ],
        ),
    ]
