# Generated by Django 4.1.7 on 2023-03-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_cart_item_alter_cart_quantity_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
