# Generated by Django 4.1.7 on 2023-03-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_cart_item_cart_items_cart_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ref_code',
        ),
    ]
