# Generated by Django 4.1.7 on 2023-03-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_item_price_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
