# Generated by Django 4.1.7 on 2023-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
